VCompressor Benchmark
gaogaotiantian/viztracer pull request #268
Opened 2022-08-28 08:48 UTC by Sefank

As #249 mentioned, VCompressor is designed for a decent compress ratio. Here provides a framework of tests to easily calculate performance improvement space-wise and time-wise on specific test cases.

Note: Here, I chose to use LZMA, famous for its high compress ratio on average level, as a baseline in terms of space-wise benchmark.

TODO:
- [x] VCompressor Space-wise Benchmark
- [ ] VCompressor Time-wise Benchmark

2022-08-29 00:06 UTC, gaogaotiantian commented
It would be nice to show the compress ratio for each method.

2022-08-29 06:39 UTC, Sefank commented
> It would be nice to show the compress ratio for each method.

@gaogaotiantian It seems that compress ratio is defined by `compressed_filesize / uncompressed_filesize` academically, and anothor common definition is `100% - (compressed_filesize / uncompressed_filesize)`. idk which one would be appropriate here?

2022-08-29 16:48 UTC, gaogaotiantian commented
Could you rebase your feature branch on `origin/trace-log-compressor` to enable to CI?

2022-08-30 05:46 UTC, Sefank commented
> Could you rebase your feature branch on `origin/trace-log-compressor` to enable to CI?

I've merge this feature branch on my `origin/trace-log-compressor` branch and it seems nothing happened?

2022-08-30 05:51 UTC, gaogaotiantian commented
You need to pull the updates from upstream.

```
# add upstream
git remote add upstream https://github.com/gaogaotiantian/viztracer
# checkout your own branch
git checkout trace-log-compressor
# get the updates from my branch
git pull upstream trace-log-compressor
# checkout your feature branch
git checkout trace-log-compressor-benchmark
# rebase on your updated trace-log-compressor
git rebase trace-log-compressor
# You need -f to force update your feature branch as it is rebased
git push -f origin trace-log-compressor-benchmark
```

2022-08-30 05:57 UTC, Sefank commented
> You need to pull the updates from upstream.
> 
> ```
> # add upstream
> git remote add upstream https://github.com/gaogaotiantian/viztracer
> # checkout your own branch
> git checkout trace-log-compressor
> # get the updates from my branch
> git pull upstream trace-log-compressor
> # checkout your feature branch
> git checkout trace-log-compressor-benchmark
> # rebase on your updated trace-log-compressor
> git rebase trace-log-compressor
> # You need -f to force update your feature branch as it is rebased
> git push -f origin trace-log-compressor-benchmark
> ```

OK done. Many thanks!

2022-08-30 06:35 UTC, Sefank commented
aha it seems we have a prerequisite pr #273  need to be reviewed first :D

2022-08-30 18:41 UTC, gaogaotiantian commented
#273 is merged in and could you rebase on that again? Thanks!

2022-08-31 05:25 UTC, Sefank commented
> #273 is merged in and could you rebase on that again? Thanks!

Done!

2022-09-03 05:33 UTC, Sefank commented
@gaogaotiantian The reason why I determined to put `_benchmark` decorator outside the class scope is that idk how to make it compatible with the decoration mechanism.

- If I move the `_benchmark` decorator into the class definition (of course adding `self` parameter first), it would just throw an error:

  > TypeError: _benchmark() missing 1 required positional argument: 'benchmark_process'
  
  I believed that it is because decorator functions should always wrap the first parameter, which would conflict with the requirement of a method function.
- And then, I tried to add `@staticmethod` for `_benchmark` to avoid the `self` being the first parameter, and it would still throw an error:

  > TypeError: 'staticmethod' object is not callable
  
  idk what's happened.

--- 

As for `BenchmarkResult`, putting it outside the class scope is for reference clarity, as the class name `TestVCompressorPerformance` is too long when the `_benchmark` decorator is also outsides the class scope. If I put it inside the class scope, I have to use it like `TestVCompressorPerformance.BenchmarkResult`.

2022-09-03 16:47 UTC, gaogaotiantian commented
You only need to move the whole `_benchmark` function into the class *without* adding the `self` argument.

The other thing worth mentioning is that your `loop_time` argument of the decorator can not be used. You need some extra code to make that work.

2022-09-04 08:38 UTC, Sefank commented
> You only need to move the whole `_benchmark` function into the class _without_ adding the `self` argument.
> The other thing worth mentioning is that your `loop_time` argument of the decorator can not be used. You need some extra code to make that work.

I've tried to write a minimal demo on the problem:

```python
class Demo:
    def deco(*args, **kargs):
        print(args)
        print(kargs)
        def _wrapper(*args, **kargs):
            pass
        return _wrapper

    @deco
    def func(self):
        pass

demo = Demo()
demo.func()
```
And this code works as expected and the output is as follows.
```
(<function Demo.func at 0x7f54138b48c8>,)
{}
```
> "as expected " just means the first positional argument is the decorated function. However, I'm stil confused about why it would work that the first positional argument of `deco` **method** is not a "self" object, or not a `Demo` instance here.

If I add a randomly chosen parameter for the `deco` like this:
```python
# ...
    @deco(p=5)
    def func(self):
        pass
# ...
```
It will throw an errror:
```
()
{'p': 5}
Traceback (most recent call last):
  File "demo.py", line 14, in <module>
    demo.func()
TypeError: 'NoneType' object is not callable
```
According to the output, the argument that should be the decorated function is magically missing. Only parameter(s) for the decorator is/are left. And it seems that the return value of the decorator changed to a `None` instead of the wrapper function.

If now I change the return value of the wrapper function like this:
```python
# ...
    def deco(*args, **kargs):
        print(args)
        print(kargs)
        def _wrapper(*args, **kargs):
            return 123
        return _wrapper
# ...
```
Error info:
```
TypeError: 'int' object is not callable
```
It seems that the return value of the decorator changes to the return value of the wrapper function.

I'm more confused right now. Is there any part that I miss?

2022-09-04 16:25 UTC, gaogaotiantian commented
This is a two-piece question. I'll make a video about the decorator in class part because that's actually a pretty common requirements. However, the answer could still be found(with some thoughts) in

https://www.bilibili.com/video/BV1mB4y1m7FT/

> It seems that the return value of the decorator changes to the return value of the wrapper function.

I'd recommend https://www.bilibili.com/video/BV19U4y1d79C/ for its answer. It's not about the class anymore. It's about how to make a decorator support usage with and without arguments. Like I said in my previous comment, your `loop_time` will never work, even in the globally defined decorator.

2022-09-04 16:45 UTC, Sefank commented
> This is a two-piece question. I'll make a video about the decorator in class part because that's actually a pretty common requirements. However, the answer could still be found(with some thoughts) in
> 
> https://www.bilibili.com/video/BV1mB4y1m7FT/
> 
> > It seems that the return value of the decorator changes to the return value of the wrapper function.
> 
> I'd recommend https://www.bilibili.com/video/BV19U4y1d79C/ for its answer. It's not about the class anymore. It's about how to make a decorator support usage with and without arguments. Like I said in my previous comment, your `loop_time` will never work, even in the globally defined decorator.

OK. I'll check it out. Thanks again!

2022-09-05 15:17 UTC, Sefank commented
I've put up an output example of this benchmark test in the top post.

2022-09-07 20:26 UTC, gaogaotiantian approved these changes

2022-09-07 20:27 UTC, gaogaotiantian requested changes

2022-09-07 20:27 UTC, gaogaotiantian commented on tests/test_vcompressor.py
> +                                      vcompress_result, other_results, subtest_idx=subtest_idx)
Please fix the indent for the linter :)

2022-09-08 05:12 UTC, gaogaotiantian commented
@Sefank is there a way to confirm the requested change is made before requesting a review? I'm seeing the review request but my change request is still there.

2022-09-08 05:49 UTC, gaogaotiantian approved these changes

2022-09-08 05:49 UTC, merged

2022-09-08 23:00 UTC, Sefank commented
> @Sefank is there a way to confirm the requested change is made before requesting a review? I'm seeing the review request but my change request is still there.

I don't really know much about it. I guess that giving it a new review with approval would be ok and previous change-requested reviews just appears here for history record?