some code cleanups and python 3 adjustments
gaogaotiantian/viztracer pull request #344
Opened 2023-06-09 02:17 UTC by marksmayo

cleaned up imports
replaced format strings with f-strings
removed trailing newlines
replaced exit() with sys.exit()
py3 doesn't need inheritance from object, fixed a few of those
replaced a deprecated call to warn() with warning()
fixed a bunch of flake8 warnings (indicated in that commit)

pytest run, I'm actually getting failures, but the same ones that failed before I started these changes, so considering it ok for now.

2023-06-09 03:11 UTC, gaogaotiantian commented
Thanks for taking the effort to do this!

I have a couple of comments, the things that I did not mention, I liked them and they'll be accepted.
1. Are you using `flake8` directly or did you add some extensions? `flake8` is what the github action lint uses so there should not be many warnings. If there are some configurations that you recommend, you can update it in `.github/workflows/lint.yaml`.
2. For trailing commas, I'm okay for those where there's a possibility to extend and there are multiple elements. However, I found it really weird for adding a trailing comma for a single item(or single line). Sometimes I used multiline just to avoid having a really long line. I hope that you can revert changes for the single item ones.
3. Please do not change anything in `src/viztracer/attach_process` and `src/viztracer/web_dist`, that's 3rd party code. The code in `tests/archived` will be deprecated soon so do not change anything in it either. Also, leave `docs/conf.py` alone.
4. You removed `ModuleNotFoundError`, then that except does not need the parenthesis anymore.

Thank you agian for working on this!

2023-06-09 03:39 UTC, marksmayo commented
1) Flake8, I have Installed plugins: flake8-2020: 1.7.0, flake8-bandit: 4.1.1, flake8-bugbear: 23.3.23, flake8-builtins: 2.1.0, flake8-commas: 2.1.0, flake8-comprehensions: 3.12.0, flake8-datetimez: 20.10.0, flake8-docstrings:
1.7.0, flake8-mutable: 1.2.0, flake8-noqa: 1.3.1, flake8-pie: 0.16.0, flake8-pytest-style: 1.7.2, flake8-return: 1.2.0, flake8_simplify: 0.20.0, mccabe: 0.7.0, pep8-naming: 0.13.3, pycodestyle: 2.10.0,
pyflakes: 3.0.1 installed.  Thoughts?
2) this is based on flake8-commas, and recommendations from more recent versions of python standards...up to you?
3. fair, I'll undo
4. good point!

2023-06-09 03:48 UTC, gaogaotiantian commented
The plugins are too much. I think the official flake8 works for me at this point.

I'll take a look at all the trailing comma fixes and see if there's anything that I hate, maybe it can be rewritten in another way.

2023-06-10 21:17 UTC, gaogaotiantian requested changes
I went through all the changes and left comments on the lines that I'd like some changes. Most of them were:
1. Lines between import section and the code. I think your linter likes one line between the import section and non-definition code. However, I'd like to keep the import section two lines away from any code(except for those that can be considered part of the import section).
2. Ways to avoid a trailing comma at a weird position.

Thank you for the work on this!

2023-06-10 21:17 UTC, gaogaotiantian commented on src/viztracer/__main__.py
> -
The style of blank lines between import and the code is inconsistent in CPython repo itself. However, I'd like to keep 2 lines, so let's revert all the line reductions(except for the line between `__all__` and import, I can consider `__all__` as part of import)

2023-06-10 21:17 UTC, gaogaotiantian commented on src/viztracer/viewer.py
> -
2 lines here.

2023-06-10 21:17 UTC, gaogaotiantian commented on src/viztracer/vizevent.py
> -
This is fine, part of import.

2023-06-10 21:17 UTC, gaogaotiantian commented on src/viztracer/vizplugin.py
> -
This is fine too

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/archived/_test_simulator.py
> -
two lines here

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/base_tmpl.py
> -
two here

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/cmdline_tmpl.py
> +from .base_tmpl import BaseTmpl
Extra line here

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/data/vdb_basic.py
> +
As we are cleaning code here, could you remove all the comments related to `wthell` or `wth`? I think those are left there when I was debugging.

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/data/vdb_basic.py
> +
The commented exception raising as well

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_basic.py
> +                    ["ls result_my_function2*.json"], shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
I don't like the comma here, let's do something like

```python
a = subprocess.run(["ls result_my_function2*.json"],
                   shell=True,
                   stdout=subprocess.PIPE,
                   stderr=subprocess.PIPE)
```

Same for the code below.

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_cmdline.py
> -
2 lines here

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_codemonkey.py
> +            """,
Just move the parenthesis up to avoid this comma.

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_flamegraph.py
> +            {"ph": "M", "pid": 1, "tid": 1, "name": "thread_name", "args": {"name": "MainThread"}},
Move the parenthesis up to avoid this comma

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_functree.py
> +from .base_tmpl import BaseTmpl
Extra line here

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_logsparse.py
> +from .cmdline_tmpl import CmdlineTmpl
Extra line here

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_multiprocess.py
> +from .cmdline_tmpl import CmdlineTmpl
Extra line here

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_patch.py
> +from .cmdline_tmpl import CmdlineTmpl
Extra line

2023-06-10 21:17 UTC, gaogaotiantian commented on tests/test_vizplugin.py
> +        if m_type == "command" and payload["cmd_type"] == "terminate":
Please revert this change - this is the structure left for future development. Currently there is only one command `terminate`, but it's possible that there are more in the future.

2023-06-18 17:53 UTC, gaogaotiantian commented
Hi @marksmayo, are you still interested in working on this PR? If not, I can make changes based on your current code. Thanks!

2023-06-25 17:42 UTC, gaogaotiantian commented
Hi @marksmayo , your contribution is greatly appreciated. As I'm preparing for v0.16.0 release, I want the changes in soon. So I'll merge this in a feature PR and make some changes there myself, then merge into main branch. I'll list you as the co-author. Thank you!

2023-06-25 17:44 UTC, merged

2023-07-03 00:39 UTC, marksmayo commented
@gaogaotiantian apologies, I'd been locked out of my github when changing phones.  All fixed now, glad to see this merged :)

2023-07-03 00:40 UTC, gaogaotiantian commented
@marksmayo no worries! Thanks for the contribution! I'm glad the ancient coding style issues are fixed.